#!/bin/bash

find -type f -name '*~' -delete

cd Runtime/

clang -DLLVM_BUILD -DLLVM_NULLPTR -S -emit-llvm main.cpp

rm -rf ./src/runtime.stg

cat main.ll | sed -e "s/</\\\\</g" | sed -e "/REPLACE_ME-GLOBAL_VARIABLES/c\<variables :{ variable | <variable><\\\\n>}>" | sed -e "/REPLACE_ME-FUNCTIONS/c\<functions :{ function | <function><\\\\n>}>" | sed -e "/REPLACE_ME-CALL_DEFINED_MAIN/c\ call void @GazFunc_main()" | sed -e "/REPLACE_ME-GLOBAL_INITS/c\<code :{ line | <line><\\\\n>}>" | sed -e "/REPLACE_ME-STRUCTS/c\<structs :{ struct | <struct><\\\\n>}>" | sed -e "1s/^/runtime(variables, functions, code, structs) ::= <<\n/" | sed -e "\$a>>" > ../src/runtime.stg
